### ISSUE TITLE
Can't find subtitles, new result data format

### ISSUE THREAD

**Issue by velp** [opensubtitles/service.subtitles.opensubtitles_by_opensubtitles#16]
Addon fails with error in log file:

```
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'dict' object has no attribute 'sort'
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.subtitles.opensubtitles_by_opensubtitles-master/service.py", line 210, in <module>
    Search(item)
  File "/storage/.kodi/addons/service.subtitles.opensubtitles_by_opensubtitles-master/service.py", line 43, in Search
    search_data.sort(key=lambda x: [not x['MatchedBy'] == 'moviehash',
AttributeError: 'dict' object has no attribute 'sort'
-->End of Python script error report<--
```
because received data has a new format, for example, see: https://pastebin.com/QgpMjJAq
it's data which received in line: https://github.com/opensubtitles/service.subtitles.opensubtitles_by_opensubtitles/blob/master/service.py#L36
In the new format data is a dict not a list.

**Comment by Trefex** [comment]
Seems to work. Please @burekas7 @opensubtitles merge the MR soon 👍

**Comment by burekas7** [comment]
Thanks, I checked you fix and it's ok.
But I don't have the write access to confirm the PR.

You should write about this in the official forum:
https://forum.opensubtitles.org/viewforum.php?f=8&sid=211c93c1d97334f5e4476691e3f22215

I will try to remind him also with private message.

**Comment by velp** [comment]
I see other user already has this problem: https://forum.opensubtitles.org/viewtopic.php?f=8&t=15847&start=105#p39738
I wrote post in the official forum but it awaits moderation.

**Comment by ironashram** [comment]
applied patch manually and i confirm it's working well

**Comment by vid0** [comment]
patch works like a charm 👍

**Comment by issy1978** [comment]
what i have to patch where to get it fixed please not to familiar with github and things like this sorry

**Comment by issy1978** [comment]
@velp @vid0 @ironashram  what do i have to do exactly to get the addon fixed please

**Comment by ironashram** [comment]
@issy1978 <br>
browse your Kodi setup to something like C:\Users\YourUser\AppData\Roaming\Kodi\addons\service.subtitles.opensubtitles_by_opensubtitles <br>
Edit service.py with a text editor and add the lines modified in the following commit
https://github.com/velp/service.subtitles.opensubtitles_by_opensubtitles/commit/6b25c9eea0ca32ccadda006a46ad84fdf07f7ca2
after line:
if search_data != None:

**Comment by issy1978** [comment]
@ironashram cant open this link get 404 error

**Comment by velp** [comment]
@issy1978, for manually fix, you can:

1. go to addon's directory (for example Kodi in OpenELEC is using: ~/.kodi/addons/service.subtitles.opensubtitles_by_opensubtitles-master)
2. open file service.py in a text editor
3. add string `search_data = search_data.values()` after line `if search_data != None:` (line number 43)

But you should not forget to add 4 spaces to the beginning of the new line from point 3, it's very important. Eventually, you must see something like:

```python
  if search_data != None:
    search_data = search_data.values()
```

**Comment by bezik46** [comment]
@ velp, so either 3 lines or this one liner, thanks!

**Comment by opensubtitles** [comment]
it is fixed now. Sorry. There was reordering by SCORE done, but index stays, so it produces this error. Please check yourself. Also we are introducing REST for search, example:
https://rest.opensubtitles.org/search/imdbid-0133093/sublanguageid-eng
(you can use any valid arguments same like in SearchSubtitles). It is cached, fast and effective

**Comment by velp** [comment]
@scerazy, the three-line option more correct because of checks old format.

**Comment by velp** [comment]
@opensubtitles, where can I see some documentation about new API? Maybe I fix the addon to work with the new API.

**Comment by pitsi** [comment]
When can we expect the patch to be merged with upstream and a new, patched version of service.subtitles.opensubtitles_by_opensubtitles ready for installation in kodi?

**Comment by velp** [comment]
@pitsi, AFAIU currently addon works fine without this patch. This issue will be closed.

**Comment by hadifarnoud** [comment]
@velp addon does not work for me with or without this patch!
