### ISSUE TITLE
Can't download subtitles

### ISSUE THREAD

**Issue by j08rebelo** [opensubtitles/service.subtitles.opensubtitles_by_opensubtitles#18]
Can anyone help me? I can't download any subtitles since the last two days. Here's the log:

23:17:04.351 T:1397748656   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'dict' object has no attribute 'sort'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/service.subtitles.opensubtitles/service.py", line 178, in <module>
                                                Search(item)
                                              File "/home/pi/.kodi/addons/service.subtitles.opensubtitles/service.py", line 44, in Search
                                                search_data.sort(key=lambda x: [not x['MatchedBy'] == 'moviehash',
                                            AttributeError: 'dict' object has no attribute 'sort'
                                            -->End of Python script error report<--
23:17:04.500 T:1750197168   ERROR: GetDirectory - Error getting plugin://service.subtitles.opensubtitles/?action=search&languages=English%2cPortuguese%2cPortuguese%20(Brazil)&preferredlanguage=Portuguese

**Comment by velp** [comment]
Issue about this problem already opened and has some fix, see: #16

**Comment by j08rebelo** [comment]
What exacly is the fix? What can i do?

**Comment by tomtomclub** [comment]
yes i can not see the fix 👍  ah i see #16

**Comment by j08rebelo** [comment]
I got it. I manually made the changes in the service.py file and it works!

**Comment by issy1978** [comment]
which line i have to change in service.py to fix it not to familiar with this j08rebelo

**Comment by j08rebelo** [comment]
Change the service.py

https://github.com/opensubtitles/service.subtitles.opensubtitles_by_opensubtitles/pull/17/files


A dom, 25/03/2018, 06:51, issy1978 <notifications@github.com> escreveu:

**Comment by j08rebelo** [comment]
Change the service.py 

https://github.com/opensubtitles/service.subtitles.opensubtitles_by_opensubtitles/pull/17/files

**Comment by opensubtitles** [comment]
it should be fixed and not need to patch anything.
