### ISSUE TITLE
Not working, error 503 Backend fetch failed

### ISSUE THREAD

**Issue by cmvac** [opensubtitles/service.subtitles.opensubtitles_by_opensubtitles#4]
Hi, the addon is throwing an error and not opening the subtitles since the 12th of February (yesterday). I have reinstalled it and it is still acting up. Kodi's log reveals an "Error 503 Backend fetch failed".

**Comment by firerm** [comment]
I Confirm that "Error **Searching Subtile"**

**Comment by firerm** [comment]
Fixed it was an API problem

**Comment by basigabri** [comment]
How did you fix it ?

**Comment by firerm** [comment]
Try it now ...as I said it was an API Problem from the side of opensubtitles.org. ADD ON is fine now

**Comment by cmvac** [comment]
Thank you @firerm for taking care of this bug promptly! I can confirm, it is working again!

**Comment by cmvac** [comment]
@firerm, it is still acting up, but it was working still today. 

SUBS: Error <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Backend fetch failed>

**Comment by firerm** [comment]
its because of API calls (too many connections) for me is back ONLINE again (usually this time has many calls so server goes down) it's an opensubtitles problem so we can't do anything, addon is still fine by this side :) I hope opensubtile give more power to their server ...

**Comment by firerm** [comment]
From Opesubtitles Forum (Official) :

- we have problems with API right now, specially on peak hours, so if your KODI was working before, dont change anything, it is not fault on your side.

- www and forum uses separate accounts, always use just www account info (login and pass) in KODI, opensubtitles addon

**Comment by cmvac** [comment]
Yes, I can confirm. I've warned the several FB groups where I am in and participate about what is going on with the Opensubtitles addon, so they don't have a reason to rant. :)

**Comment by opensubtitles** [comment]
When servers are overloaded, the http return code is not 200, but for example 503. There is nothing to be fixed from the side of plugin, it is server issue
