### ISSUE TITLE
Can not find any subtitles

### ISSUE THREAD

**Issue by pitsi** [opensubtitles/service.subtitles.opensubtitles_by_opensubtitles#5]
As of today, your plugin can no longer find any subtitles. The message "error searching for subtitles" pops up and nothing happens (screenshot).

![screenshot000](https://cloud.githubusercontent.com/assets/5880037/24524146/4060f77a-159e-11e7-9344-144b10d7d670.png)

And the log, if it helps
http://paste.debian.net/925188/

Kodi 17.1 on debian testing x64

**Comment by CharlesDelestre** [comment]
Same issue here. Instant "error searching for subtitles" message. Manual doesn't work anymore.

**Comment by pitsi** [comment]
It seems to be working today...

![screenshot000](https://cloud.githubusercontent.com/assets/5880037/24538543/7c693224-15f2-11e7-8cd9-834040e94260.png)

**Comment by ghost** [comment]
I've got a similar problem. But I guess it is not the fault of this plugin, but I'm testing Kodi v18 and I can't find subtitles anymore with this error in the log:

`19:41:57.769 T:3581256608   ERROR: Unable to create plugin service.subtitles.opensubtitles
19:41:57.769 T:3581256608   ERROR: GetDirectory - Error getting plugin://service.subtitles.opensubtitles/?action=search&languages=English&preferredlanguage=Unknown`

**Comment by pitsi** [comment]
Your plugin is not the same as the one in this github page. 
This page is for opensubtitles **by opensubtitles** while yours is opensubtitles (plain name and the plugin is hosted on the official kodi repo), so you should ask here for help. 

http://forum.kodi.tv/showthread.php?tid=183114

**Comment by pitsi** [comment]
I am closing the issue since it was fixed... by itself :P
