### ISSUE TITLE
Can't download subtitle

### ISSUE THREAD

**Issue by PREngineer** [opensubtitles/service.subtitles.opensubtitles_by_opensubtitles#8]
This issue started a few days ago.

I can see the subtitles but when I try to download them, it tells me that it can't be downloaded and to check the logs.

The logs say:

![failed - 1](https://cloud.githubusercontent.com/assets/6334069/25237062/9f7375d4-25b7-11e7-9105-ec07119afe9d.jpg)
![failed - 2](https://cloud.githubusercontent.com/assets/6334069/25237063/9f7718ce-25b7-11e7-9822-a24e235f02fa.jpg)
![log - 1](https://cloud.githubusercontent.com/assets/6334069/25237064/9f77f744-25b7-11e7-9fcb-319869eb47c3.jpg)
![log - 2](https://cloud.githubusercontent.com/assets/6334069/25237066/9f7d0a7c-25b7-11e7-9612-8648908776cd.jpg)
![log - 3](https://cloud.githubusercontent.com/assets/6334069/25237065/9f7a6f7e-25b7-11e7-917c-9305cf270066.jpg)

**Comment by devinamliwalla** [comment]
I’m getting can’t download too, did u get any luck?

**Comment by vastril4o** [comment]
not sure, but I thing links or the file is broken, it cant be downloaded at all.

**Comment by opensubtitles** [comment]
first of all, send your log as text file.
second, the script is making timeout, so I guess it is working now. When servers are overloaded, either it doesn't search or download.
